In [1]:
import cv2
import matplotlib.pyplot as plt
import json
import pandas as pd

# Load Data:

In [2]:
# filename will contain full address of qed.json given by the dataset

filename = f"/raid/infolab/bhavyakohli/mmdet/mmdetection/data/training_data/quadrant-enumeration-disease/train_quadrant_enumeration_disease.json"
f = json.load(open(filename))

f.keys()

dict_keys(['images', 'annotations', 'categories_1', 'categories_2', 'categories_3'])

In [28]:
f['annotations'][15]

{'iscrowd': 0,
 'image_id': 2,
 'bbox': [1824.0, 995.0, 229.0, 255.0],
 'segmentation': [[1958,
   995,
   1988,
   1026,
   2004,
   1075,
   2033,
   1143,
   2053,
   1213,
   2025,
   1244,
   1996,
   1250,
   1967,
   1246,
   1915,
   1187,
   1867,
   1122,
   1824,
   1061,
   1883,
   1017,
   1930,
   1002]],
 'id': 16,
 'area': 32812,
 'category_id_1': 2,
 'category_id_2': 6,
 'category_id_3': 1}

In [3]:
f['categories_3']

[{'id': 0, 'name': 'Impacted', 'supercategory': 'Impacted'},
 {'id': 1, 'name': 'Caries', 'supercategory': 'Caries'},
 {'id': 2, 'name': 'Periapical Lesion', 'supercategory': 'Periapical Lesion'},
 {'id': 3, 'name': 'Deep Caries', 'supercategory': 'Deep Caries'}]

In [4]:
f['annotations'][0].keys()

dict_keys(['iscrowd', 'image_id', 'bbox', 'segmentation', 'id', 'area', 'category_id_1', 'category_id_2', 'category_id_3'])

In [5]:
# take annotations from the qed.jsona and convert it into a sorted dataframe

annos = pd.DataFrame.from_dict(f['annotations'], orient='columns')
annos.drop(columns = ["iscrowd", "segmentation", "area"], axis=1, inplace=True)
annos.sort_values(by = ["image_id", "category_id_1", "category_id_2"], inplace = True)

# Performing some checks

In [6]:
#annots = [{"iscrowd": 0, "image_id": 1, "bbox": [542.0, 698.0, 220.0, 271.0], "segmentation": [[621, 703, 573, 744, 542, 885, 580, 945, 650, 969, 711, 883, 762, 807, 748, 741, 649, 698]], "id": 1, "area": 39683, "category_id_1": 3, "category_id_2": 7, "category_id_3": 0}, {"iscrowd": 0, "image_id": 1, "bbox": [1952.0, 693.0, 177.0, 270.0], "segmentation": [[2045, 693, 2109, 734, 2129, 915, 2047, 963, 2009, 909, 1973, 851, 1955, 782, 1952, 730, 2000, 702]], "id": 2, "area": 33301, "category_id_1": 2, "category_id_2": 7, "category_id_3": 0}, {"iscrowd": 0, "image_id": 1, "bbox": [675.0, 708.0, 243.0, 300.0], "segmentation": [[784, 711, 754, 746, 737, 821, 678, 916, 675, 986, 690, 1003, 727, 1008, 787, 998, 851, 925, 885, 857, 918, 807, 916, 763, 882, 720, 827, 708]], "id": 3, "area": 45758, "category_id_1": 3, "category_id_2": 6, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1463.0, 725.0, 98.0, 425.0], "segmentation": [[1464, 749, 1513, 725, 1550, 760, 1555, 798, 1548, 887, 1561, 1147, 1510, 1150, 1488, 1039, 1463, 873, 1463, 778]], "id": 4, "area": 30985, "category_id_1": 2, "category_id_2": 2, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1536.0, 753.0, 103.0, 381.0], "segmentation": [[1543, 796, 1590, 753, 1622, 796, 1629, 840, 1623, 890, 1639, 1111, 1596, 1134, 1565, 1077, 1544, 974, 1536, 852, 1536, 805]], "id": 5, "area": 28044, "category_id_1": 2, "category_id_2": 3, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1600.0, 762.0, 122.0, 337.0], "segmentation": [[1605, 797, 1646, 762, 1684, 785, 1701, 852, 1722, 1095, 1684, 1099, 1645, 1030, 1621, 884, 1600, 825]], "id": 6, "area": 24348, "category_id_1": 2, "category_id_2": 4, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1701.0, 371.0, 145.0, 290.0], "segmentation": [[1716, 409, 1711, 543, 1701, 604, 1713, 651, 1770, 661, 1827, 636, 1831, 531, 1846, 396, 1835, 371, 1759, 371, 1730, 384]], "id": 7, "area": 34145, "category_id_1": 1, "category_id_2": 5, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [779.0, 376.0, 132.0, 317.0], "segmentation": [[779, 487, 791, 631, 800, 680, 822, 692, 894, 693, 911, 654, 910, 594, 887, 535, 856, 396, 816, 376, 779, 406]], "id": 8, "area": 31064, "category_id_1": 0, "category_id_2": 6, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1667.0, 723.0, 237.0, 356.0], "segmentation": [[1667, 784, 1689, 747, 1741, 753, 1802, 723, 1816, 767, 1833, 873, 1904, 1023, 1784, 1079, 1725, 996, 1694, 878, 1668, 808]], "id": 9, "area": 46556, "category_id_1": 2, "category_id_2": 5, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1806.0, 696.0, 237.0, 308.0], "segmentation": [[1843, 724, 1806, 745, 1807, 800, 1857, 901, 1921, 998, 2011, 1004, 2043, 959, 1999, 871, 1969, 803, 1950, 734, 1908, 696]], "id": 10, "area": 42235, "category_id_1": 2, "category_id_2": 6, "category_id_3": 1}, {"iscrowd": 0, "image_id": 1, "bbox": [1405.1948051948052, 724.6753246753246, 75.32467532467535, 353.2467532467533], "segmentation": [[1418, 724, 1476, 729, 1466, 841, 1477, 941, 1480, 1075, 1419, 1077, 1409, 931, 1405, 790]], "id": 11, "area": 22286, "category_id_1": 2, "category_id_2": 1, "category_id_3": 2}, {"iscrowd": 0, "image_id": 1, "bbox": [1344.155844155844, 720.7792207792207, 77.92207792207796, 385.71428571428567], "segmentation": [[1414, 720, 1403, 909, 1422, 1089, 1346, 1106, 1346, 887, 1344, 725]], "id": 12, "area": 24371, "category_id_1": 2, "category_id_2": 0, "category_id_3": 2}, {"iscrowd": 0, "image_id": 1, "bbox": [1288.3116883116884, 723.3766233766233, 62.33766233766232, 387.0129870129871], "segmentation": [[1344, 728, 1350, 1110, 1290, 1092, 1290, 962, 1288, 723]], "id": 13, "area": 21469, "category_id_1": 3, "category_id_2": 0, "category_id_3": 2}]

In [7]:
# image = cv2.imread("train_673.png")
# for dic in annots:
#   x_min, y_min, width, height = dic['bbox'][:]

#   x_max = x_min + width
#   y_max = y_min + height

#   if dic["category_id_1"] == 0:
#     color = (255, 0, 0)    #red
#   elif dic["category_id_1"] == 1:
#     color = (0, 255, 0)   #green
#   elif dic["category_id_1"] == 2:
#     color = (0, 0, 255)   #blue
#   elif dic["category_id_1"] == 3:
#     color = (0, 0,0)      #black
#   thickness = 5
#   cv2.rectangle(image, (int(x_min), int(y_min)), (int(x_max), int(y_max)), color, thickness)

# plt.imshow(image)

# Run through M1

In [14]:
from tqdm import tqdm

In [8]:
import sys, os
sys.path.append("/raid/infolab/bhavyakohli/mmdet/Co-DETR/")
import warnings
warnings.filterwarnings(action='ignore', category=DeprecationWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)

from tqdm import tqdm
from mmdet.apis import *

# Setup a checkpoint file to load
m1_checkpoint = '../experiments/quadrant_codetr/latest.pth'
m1_configpath = '../experiments/quadrant_codetr/co_dino_5scale_r50_1x_coco_quadrant.py'

model1 = init_detector(m1_configpath, m1_checkpoint)

m2_checkpoint = '../experiments/enumeration_codetr_ver2/latest.pth'
m2_configpath = '../experiments/enumeration_codetr_ver2/co_dino_5scale_r50_1x_coco_enumeration.py'

model2 = init_detector(m2_configpath, m2_checkpoint)

2024-04-08 14:55:30,749 - mmcv - INFO - initialize RPNHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01}
2024-04-08 14:55:30,758 - mmcv - INFO - 
rpn_conv.weight - torch.Size([256, 256, 3, 3]): 
NormalInit: mean=0, std=0.01, bias=0 
 
2024-04-08 14:55:30,758 - mmcv - INFO - 
rpn_conv.bias - torch.Size([256]): 
NormalInit: mean=0, std=0.01, bias=0 
 
2024-04-08 14:55:30,759 - mmcv - INFO - 
rpn_cls.weight - torch.Size([9, 256, 1, 1]): 
NormalInit: mean=0, std=0.01, bias=0 
 
2024-04-08 14:55:30,759 - mmcv - INFO - 
rpn_cls.bias - torch.Size([9]): 
NormalInit: mean=0, std=0.01, bias=0 
 
2024-04-08 14:55:30,759 - mmcv - INFO - 
rpn_reg.weight - torch.Size([36, 256, 1, 1]): 
NormalInit: mean=0, std=0.01, bias=0 
 
2024-04-08 14:55:30,760 - mmcv - INFO - 
rpn_reg.bias - torch.Size([36]): 
NormalInit: mean=0, std=0.01, bias=0 
 
2024-04-08 14:55:30,839 - mmcv - INFO - initialize Shared2FCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'

In [9]:
# we read images in our third dataset here

image_filepath = "/raid/infolab/bhavyakohli/mmdet/mmdetection/data/training_data/quadrant-enumeration-disease/xrays/"     #where images are stored
images = [image_filepath+imageinfo['file_name'] for imageinfo in f['images']]
len(images)

705

In [13]:
# obtain results by running model1 on the images read in the previous block
# KOHLI NOTE: I'm assuming quad_results contains one singular bbox and not
# the entire possibility thing you had mentioned,
# please ensure that's done here or at the spot I'm indicating in the next block

# results had topleft_x, topleft_y, bottomright_x, bottomright_y, category of quadrant

quad_results = []
for imagepath in tqdm(images):
    result = inference_detector(model1, imagepath)
    result = [r[0][:-1] for r in result]
    quad_results.append(result)

# quad_results = model1(images)["some subset"]

In [21]:
# time for patch extraction

qlocation = "/raid/infolab/bhavyakohli/mmdet/mmdetection/data/training_data/quadrant-enumeration-disease/qpatches/"        # where to store patches
os.makedirs(qlocation, exist_ok=True)
qimagenames = []      # this will contain image names (WITHOUT the directory part)
for i in tqdm(range(len(images))):
    photo = cv2.imread(images[i])
    patches = [0,0,0,0]
    result = quad_results[i]
    for j in range(4):
        x_min, y_min, x_max, y_max, cat = *result[j], j       # KOHLI NOTE: This is the second spot that I was talking about
        # adjust for category mismatch in data
        if cat==0:
            cat=1
        elif cat==1:
            cat=0
        # patch extraction and flipping
        x_min, y_min, x_max, y_max = int(x_min), int(y_min), int(x_max), int(y_max)
        patch = photo[y_min:y_max, x_min:x_max]
        if cat == 1 or cat == 2:
            patch = cv2.flip(patch, 1)
        if cat == 2 or cat == 3:
            patch = cv2.flip(patch, 0)
        # saving the patch
        filename = f"patch_{i}_{cat}.png"      # amru wants image_id format, hence the i in the file name
        patches[cat] = filename
        cv2.imwrite(qlocation+filename, patch)
    qimagenames += patches

100%|██████████| 705/705 [01:26<00:00,  8.17it/s]


# Run through M2

In [25]:
# creating a full address to the images and running them through model2
# KOHLI NOTE: Same assumption as before, will highlight the second
# possible spot in the next block, make those changes if required

qimages = [qlocation+name for name in qimagenames]

enumresults = []
for qimagepath in tqdm(qimages):
    result = inference_detector(model2, qimagepath)
    result = [r[0][:-1] for r in result]
    enumresults.append(result)

100%|██████████| 2820/2820 [09:41<00:00,  4.85it/s]


In [37]:
enumresults[8]

[array([670.7224  ,  79.786156, 770.6734  , 411.48807 ], dtype=float32),
 array([583.12665 ,  36.521454, 688.2596  , 400.9741  ], dtype=float32),
 array([490.51907 ,  24.133528, 607.20654 , 408.92926 ], dtype=float32),
 array([414.8592 ,  43.59919, 534.826  , 388.38278], dtype=float32),
 array([349.67078 ,  34.495018, 482.59744 , 374.0385  ], dtype=float32),
 array([131.31407 ,  20.695469, 270.5533  , 335.79468 ], dtype=float32),
 array([131.31407 ,  20.695469, 270.5533  , 335.79468 ], dtype=float32),
 array([131.31407 ,  20.695469, 270.5533  , 335.79468 ], dtype=float32)]

In [41]:
cat1

'3'

In [45]:
# tooth patch extraction, pretty straightforward
# iterating over the annos dataframe to check if the given tooth
# has a category associated to it, if not, given cat3 = 4 (normal)

toothlocation = "/raid/infolab/bhavyakohli/mmdet/mmdetection/data/training_data/quadrant-enumeration-disease/tpatches/"        # where to store patches of teeth
os.makedirs(toothlocation, exist_ok=True)

k=0                       # move through annos
m = annos.shape[0]
patch_size = (380, 550)   # width, height

for i in tqdm(range(len(qimages))):
    photo = cv2.imread(qimages[i])
    name = qimagenames[i]
    id, cat1 = [int(i) for i in name[6:-4].split('_')]

    for j, result in enumerate(enumresults[i]):
        x_min, y_min, x_max, y_max, cat2 = *result, j            # KOHLI NOTE: Second spot
        x_min, y_min, x_max, y_max = int(x_min), int(y_min), int(x_max), int(y_max)
        patch = photo[y_min:y_max, x_min:x_max]
        height = y_max - y_min
        width = x_max - x_min

        # Resize patch [image may be bigger than given patch_size :(]
        toppad, bottompad, leftpad, rightpad = [0,0,0,0]
        if height < patch_size[1]:
            toppad = int((patch_size[1] - height)/2)
            bottompad = int(patch_size[1] - height - toppad)
        if width < patch_size[0]:
            leftpad = int((patch_size[0] - width)/2)
            rightpad = int(patch_size[0] - width - leftpad)
        patch = cv2.copyMakeBorder(
                patch, toppad, bottompad, leftpad, rightpad,
                cv2.BORDER_CONSTANT, value=[0,0,0])
        patch = cv2.resize(patch, patch_size, interpolation = cv2.INTER_AREA)

        while annos.iloc[k]['image_id'] == id:
            while annos.iloc[k]['category_id_1'] == cat1:
                if annos.iloc[k]['category_id_2'] == cat2:
                    cat3 = annos.iloc[k]['category_id_3']
                    filename = toothlocation + f"patch_{id}_{cat1}_{cat2}_{cat3}.png"
                    cv2.imwrite(filename, patch)
                    k += 1
                    if k==m:
                        break
                else:
                    cat3 = 4
                    filename = toothlocation + f"patch_{id}_{cat1}_{cat2}_{cat3}.png"
                    cv2.imwrite(filename, patch)
                    k += 1
                    if k==m:
                        break

  0%|          | 4/2820 [00:20<3:57:33,  5.06s/it]


KeyboardInterrupt: 

In [ ]:
# strd = "patch_234_5.png"
# strd[6:-4].split('_')

['234', '5']